api/adminUserAPI.ts, app/admin/notice-manage/[noticeId]/_components/NoticeDetailPage.tsx, app/admin/professor-manage/edit/_components/EditProfessorForm.tsx, app/admin/professor-manage/edit/page.tsx, app/admin/professor-manage/enroll/_components/CreateProfessorForm.tsx, app/admin/professor-manage/enroll/page.tsx, app/admin/professor-manage/list/_components/ProfessorManageTable.tsx, app/admin/professor-manage/list/page.tsx, app/admin/professor-manage/page.tsx, app/admin/user-manage/edit/_components/EditUserForm.tsx, app/admin/user-manage/enroll/_components/CreateUserForm.tsx, pnpm-lock.yaml, types/admin/notice.ts
- closed #86
어떤 변경 사항이 있나요?
---
교수 등록 API 역할 부분 수정 필요하며, 데이터 fetch 관련 수정할 예정입니다.
=> [feat] 교수 관리 창 화면 구현 및 api 연동

api/adminProblemAPI.ts, app/admin/problem-manage/_components/ProblemManageTable.tsx, app/admin/professor-manage/enroll/_components/CreateProfessorForm.tsx, app/admin/professor-manage/list/_components/ProfessorManageTable.tsx, app/admin/user-manage/edit/page.tsx, app/admin/user-manage/list/_components/userManageTable.tsx, types/admin/problem.ts
- closed #89
문제 목록 페이지 api 연동 및 검색기능 구현 완료했습니다.
어떤 변경 사항이 있나요?
---
=> [feat] 문제 목록 페이지 api 연동

api/authAPI.ts, api/inquiryAPI.ts, api/memberAPI.ts, api/noticeAPI.ts, api/problemAPI.ts, app/(site)/inquiry/[inquiryId]/page.tsx, app/(site)/inquiry/_components/InquiryTable.tsx, app/(site)/inquiry/write/InquiryForm.tsx, app/(site)/main/_components/MainProblem.tsx, app/(site)/notice/[noticeId]/page.tsx, app/(site)/profile/@modal/(.)withdrawal/page.tsx, app/(site)/profile/@modal/default.tsx, app/(site)/profile/_components/LanguageForm.tsx, app/(site)/profile/_components/MemberProblemTable.tsx, app/(site)/profile/layout.tsx, app/(site)/profile/page.tsx, app/(site)/profile/withdrawal/page.tsx, app/admin/problem-manage/_components/ProblemManageTable.tsx, app/algorithm-ide/_components/IdeProblemWindow.tsx, components/badge/DiffBadge.tsx, components/card/RecProblemCard.tsx, components/modal/ModalLarge.tsx, constants/difficultyColorMap.ts, mocks/PROBLEM_MOCK_DATA.json, pnpm-lock.yaml, types/admin/problem.ts, types/inquiry.ts, types/notice.ts, types/problem.ts
- closed #84 
공지사항 상세 조회, 문의사항 작성, 문의사항 상세 조회 페이지를 구현 및 api 연동하고
사용자 페이지의 선호 언어, 탈퇴 부분을 구현하였습니다.
또한, 공통 알림 모달 컴포넌트를 구현하였습니다.
어떤 변경 사항이 있나요?
---
=> [feat] 공지사항 상세조회 문의사항 작성 문의사항 상세조회 사용자 페이지 api 연결 공통 알림 모달 컴포넌트 구현

app/admin/contest-manage/page.tsx
- closed #103 
관리자 대회페이지 오류수정
어떤 변경 사항이 있나요?
---
관리자 대회페이지 오류수정
=> [fix] 관리자 대회페이지 오류 수정

api/adminContestAPI.ts, app/admin/exam-manage/page.tsx
- closed #105
어떤 변경 사항이 있나요?
---
=> [fix] 오류 수정

app/admin/notice-manage/[noticeId]/_components/NoticeDetailPage.tsx
- closed #105
어떤 변경 사항이 있나요?
---
=> [fix] #107 오류 수정

api/professorExamAPI.ts, api/professorInquiryAPI.ts, app/admin/inquiry-manage/[inquiryId]/_components/Inquiryreplyempty.tsx, app/admin/inquiry-manage/page.tsx, app/professor/_components/SideProfessorNav.tsx, app/professor/exam-manage/list/_components/ExamManageTable.tsx, app/professor/exam-manage/list/_components/ExamTable.tsx, app/professor/exam-manage/list/page.tsx, app/professor/inquiry/[InquiryId]/_components/Inquiryreply.tsx, app/professor/inquiry/[InquiryId]/page.tsx, app/professor/inquiry/list/_components/InquiryTable.tsx, app/professor/inquiry/list/page.tsx, app/professor/inquiry/write/_components/InquriyForm.tsx, app/professor/inquiry/write/page.tsx, types/admin/user.ts, types/professor/exam.ts, types/professor/inquiry.ts
- closed #100 
교수 관련 API 중 시험목록 조회 및 문의사항 관련 API 연동 완료했습니다.
어떤 변경 사항이 있나요?
---
=> [feat] 교수 관련 화면 및 api 연동

api/memberAPI.ts, app/(site)/_components/HeaderMemberDropdown.tsx, app/(site)/profile/_components/MemberProblemTable.tsx, app/(site)/profile/_components/ProfileCard.tsx, app/(site)/profile/_components/RatingHelperCard.tsx, app/(site)/profile/page.tsx, app/(site)/profile/settings/@modal/(.)password/page.tsx, app/(site)/profile/settings/@modal/default.tsx, app/(site)/profile/settings/layout.tsx, app/(site)/profile/settings/page.tsx, app/(site)/profile/settings/password/page.tsx, components/modal/ModalLarge.tsx, lib/axiosConfig.ts, types/member.ts, types/problem.ts
- closed #96 
사용자 대시보드, 사용자 정보 수정 페이지, 사용자 비밀번호 변경 페이지를 구현하였습니다.
개인 맞춤형 문제 리스트 API 연동은 미비된 상태로, 다음 이슈에서 해결할 예정입니다.
어떤 변경 사항이 있나요?
---
=> Feat/#96 사용자 대시보드 api 연결 사용자 정보 수정 페이지 구현

Dockerfile
- closed #113 
빌드용 도커파일의 node 버전을 일부 수정하였습니다.
어떤 변경 사항이 있나요?
---
=> [fix] #113 빌드용 도커파일 수정

.dockerignore, Dockerfile
- closed #117 
어떤 변경 사항이 있나요?
---
=> [fix] 빌드 오류 해결 및 dockerignore 추가

app/admin/admin-manage/my-account/_components/EditAdminMyAccountForm.tsx, app/admin/problem-manage/list/page.tsx, app/admin/problem-manage/page.tsx, app/professor/my-account/_components/EditProfessorMyAccountForm.tsx
- closed #122 
충돌 오류를 수정하였습니다.
어떤 변경 사항이 있나요?
---
=> [fix] 충돌 오류 수정

api/admin/adminProblemAPI.ts, app/admin/problem-manage/edit/editor/@modal/(.)testcase/page.tsx, app/admin/problem-manage/edit/editor/@modal/default.tsx, app/admin/problem-manage/edit/editor/_components/ProblemForm.tsx, app/admin/problem-manage/edit/editor/layout.tsx, app/admin/problem-manage/edit/editor/page.tsx, app/admin/problem-manage/edit/editor/testcase/page.tsx, app/admin/problem-manage/list/_components/ProblemManageTable.tsx, app/admin/user-manage/enroll/_components/CreateUserForm.tsx
- closed #127
문제 수정기능 구현
어떤 변경 사항이 있나요?
---
=> [feat] 문제 수정기능 구현

api/admin/adminExamAPI.ts, app/admin/exam-manage/enroll/@modal/(.)testcase/page.tsx, app/admin/exam-manage/enroll/@modal/default.tsx, app/admin/exam-manage/enroll/_components/AddCandidate.tsx, app/admin/exam-manage/enroll/_components/EnrollTestForm.tsx, app/admin/exam-manage/enroll/_components/ProblemForm.tsx, app/admin/exam-manage/enroll/layout.tsx, app/admin/exam-manage/enroll/page.tsx, app/admin/exam-manage/enroll/testcase/page.tsx, app/admin/exam-manage/style.css, app/admin/inquiry-manage/_components/InquiryManageTable.tsx, app/admin/problem-manage/enroll/editor/_components/ProblemForm.tsx, constants/breadCrumbsMap.ts, types/admin/exam.ts, types/admin/problem.ts
- closed #129
어떤 변경 사항이 있나요?
---
시험 등록 기능 Request는 정상 전송 확인했으나, 관련 API가 아직 미비해 정상 작동여부는 테스트 하지 못했습니다.
=> [feat] #129 시험 등록 기능 구현

app/admin/admin-manage/my-account/_components/EditAdminMyAccountForm.tsx, app/admin/exam-manage/enroll/_components/EnrollTestForm.tsx, app/admin/exam-manage/list/_components/ExamManageTable.tsx, app/admin/inquiry-manage/_components/InquiryManageTable.tsx, app/admin/notice-manage/list/_components/NoticeManageTable.tsx, app/admin/problem-manage/list/_components/ProblemManageTable.tsx, app/admin/professor-manage/edit/_components/EditProfessorForm.tsx, app/admin/professor-manage/enroll/_components/CreateProfessorForm.tsx, app/admin/professor-manage/list/_components/ProfessorManageTable.tsx, app/admin/user-manage/edit/_components/EditUserForm.tsx, app/admin/user-manage/enroll/_components/CreateUserForm.tsx, app/admin/user-manage/list/_components/userManageTable.tsx, app/not-found.tsx, app/professor/_components/GachonOJShortCut.tsx, app/professor/_components/OngoingExams.tsx, app/professor/page.tsx, components/card/ProfessorTestCard.tsx
- closed #132
어떤 변경 사항이 있나요?
---
관리자의 페이지중 라우팅이 필요한 부분을 수정하였고, 테이블들의 데이터 fetch부분을 수정하였습니다.
=> [mod] 테이블 페이지 라우팅 및 fetch 관련 코드 수정

app/(auth)/login/_components/LoginForm.tsx, app/(site)/profile/settings/page.tsx, app/algorithm-ide/_components/IdeFooter.tsx, app/layout.tsx, lib/axiosConfig.ts, package.json, pnpm-lock.yaml
- closed #95 
프론트단 권한 분리 및 강제 라우팅 처리를 진행하였습니다. 권한에 따른 목적지는 login이며, 관련된 로컬 스토리지를 초기화한 뒤 강제 이동되도록 구현하였습니다.
어떤 변경 사항이 있나요?
---
=> [feat] #95 프론트단 권한 분리 및 강제 라우팅 처리

api/problemAPI.ts, api/testAPI.ts, app/(site)/_components/HeaderLoginButton.tsx, app/(site)/problem/_components/ProblemTable.tsx, app/(site)/profile/_components/RatingHelperCard.tsx, app/(site)/profile/page.tsx, app/admin/problem-manage/enroll/editor/_components/ProblemForm.tsx, app/algorithm-ide/[problemId]/page.tsx, app/algorithm-ide/_components/IdeFooter.tsx, app/algorithm-ide/_components/IdeMain.tsx, app/algorithm-ide/_components/IdeResultWindow.tsx, app/algorithm-ide/_components/ResultModal.tsx, app/globals.css, components/card/TestCard.tsx, components/modal/ModalSmall.tsx, components/nav/manage/sidenav/SideNavAccount.tsx, lib/axiosConfig.ts, types/problem.ts
- closed #137 
다수의 CSS 수정을 진행하고, 문제 실행 및 채점 기능, 문제 테이블 관련 기능을 수정하였습니다.
어떤 변경 사항이 있나요?
---
=> [feat] 문제 채점 기능 구현 코드 분석 페이지 및 기능 구현

api/inquiryAPI.ts, api/memberAPI.ts, api/noticeAPI.ts, api/problemAPI.ts, app/(site)/inquiry/_components/InquiryTable.tsx, app/(site)/inquiry/page.tsx, app/(site)/notice/_components/NoticeTable.tsx, app/(site)/notice/page.tsx, app/(site)/problem/_components/ProblemTable.tsx, app/(site)/profile/_components/MemberProblemTable.tsx, app/(site)/ranking/_components/RankingTable.tsx, app/admin/inquiry-manage/_components/InquiryManageTable.tsx, components/pagination/PaginationBar.css
- closed #141 
어떤 변경 사항이 있나요?
---
=> Feat/#141 페이지네이션 바 구현

app/admin/inquiry-manage/[inquiryId]/_components/Inquiryreply.tsx, app/admin/inquiry-manage/[inquiryId]/page.tsx, app/admin/notice-manage/[noticeId]/_components/NoticeDetailPage.tsx, app/admin/notice-manage/enroll/_components/CreateNoticeForm.tsx, app/admin/notice-manage/list/_components/NoticeManageTable.tsx, app/admin/problem-manage/edit/editor/_components/ProblemForm.tsx, app/admin/user-manage/enroll/_components/CreateUserForm.tsx
CSS, 라우팅 처리등 잡다한 오류 및 버그들을 수정했습니다.
- closed #158
어떤 변경 사항이 있나요?
---
=> [fix] 기타 오류사항 수정

api/admin/adminExamAPI.ts, app/admin/exam-manage/edit/_components/EditExamForm.tsx, app/admin/exam-manage/edit/_components/ProblemForm.tsx, app/admin/exam-manage/enroll/_components/EnrollExamForm.tsx, app/admin/exam-manage/enroll/_components/ProblemForm.tsx, app/admin/exam-manage/result/list/[examId]/_components/ExamResultList.tsx, app/admin/problem-manage/edit/editor/_components/ProblemForm.tsx, app/professor/_components/IncorrectRateQuestions.tsx, app/professor/exam-manage/edit/_components/EditExamForm.tsx, app/professor/exam-manage/edit/_components/ProblemForm.tsx, app/professor/exam-manage/enroll/_components/EnrollExamForm.tsx, app/professor/exam-manage/enroll/_components/ProblemForm.tsx, app/professor/exam-manage/list/_components/ExamTable.tsx, app/professor/exam-manage/result/[testId]/_components/ExamResult.tsx, app/professor/exam-manage/result/[testId]/page.tsx, app/professor/exam-manage/result/list/[examId]/_components/ExamResultList.tsx, app/professor/exam-manage/result/list/[examId]/page.tsx, types/admin/exam.ts, types/admin/problem.ts
- closed #162
어떤 변경 사항이 있나요?
---
=> [feat] 교수의 시험 결과 조회 기능 구현

app/(site)/contest/[examId]/page.tsx, app/(site)/exam/[examId]/page.tsx, app/(site)/problem/feedback/[submissionId]/page.tsx, app/(site)/profile/@modal/(.)withdrawal/page.tsx, app/(site)/profile/_components/MemberProblemTable.tsx, app/(site)/profile/_components/MemberSolProblemTable.tsx, app/(site)/profile/settings/page.tsx, app/test-ide/_components/IdeMain.tsx
- closed #164 
로딩 애니메이션 및 css 수정을 진행하였습니다.
어떤 변경 사항이 있나요?
---
=> [feat] 로딩 애니메이션 및 css 수정

app/admin/contest-manage/edit/_components/EditContestForm.tsx, app/admin/contest-manage/enroll/_components/EnrollContestForm.tsx
- closed #166
어떤 변경 사항이 있나요?
---
=> [fix] type 오류수정

app/admin/contest-manage/result/list/[examId]/_components/ExamResultList.tsx
- closed #166
어떤 변경 사항이 있나요?
---
=> [fix] #166 type 오류 수정

app/(site)/_components/HeaderMemberDropdown.tsx, app/(site)/_components/HeaderNav.tsx, app/(site)/profile/_components/MemberProblemTable.tsx, app/(site)/profile/_components/MemberSolProblemTable.tsx, app/admin/admin-manage/page.tsx, app/algorithm-ide/_components/IdeHeaderMemberDropdown.tsx, app/test-ide/[examId]/page.tsx, app/test-ide/_components/IdeHeaderMemberDropdown.tsx, components/nav/manage/AdminHeader.tsx, lib/axiosConfig.ts
- closed #170 
어떤 변경 사항이 있나요?
---
=> [feat] 시험 테스트케이스 세션 관리 알고리즘 문제 코드 세션 관리 일부 api 연동 확인 ai 피드

api/admin/adminContestAPI.ts, api/admin/adminExamAPI.ts, app/admin/contest-manage/list/_component/ContestManageTable.tsx, app/admin/exam-manage/list/_components/ExamManageTable.tsx
- closed #174
어떤 변경 사항이 있나요?
---
시험 대회삭제에 사용되는 관리자 API를 수정하였습니다.
=> [mod] 시험, 대회 삭제 API 수정

README.md
- closed #157
어떤 변경 사항이 있나요?
---
=> [docs] readme 파일 작성

app/(site)/profile/_components/MemberSolProblemTable.tsx, app/algorithm-ide/_components/ResultModal.tsx
- closed #177 
ai 관련 코드 오류 수정
어떤 변경 사항이 있나요?
---
=> [feat] 버그 수정
